# Generated by Django 3.0.8 on 2020-08-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Marka')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('tech_review', models.DateField(verbose_name='Przegląd techniczny')),
                ('fridge', models.BooleanField(verbose_name='Czy jest lodówka?')),
            ],
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_id', models.CharField(max_length=50, verbose_name='Identyfikator')),
                ('name', models.CharField(max_length=50, verbose_name='Imię')),
                ('surname', models.CharField(max_length=50, verbose_name='Nazwisko')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Adres')),
                ('place', models.CharField(choices=[('pkt', 'Punkt Pobrań'), ('lab', 'Laboratorium'), ('inny', 'Inny obiekt')], max_length=20, verbose_name='Obiekt')),
                ('pickup_time', models.CharField(choices=[('6', '6.00-7.00'), ('7', '7.00-8.00'), ('8', '8.00-9.00'), ('9', '9.00-10.00'), ('10', '10.00-11.00'), ('11', '11.00-12.00'), ('12', '12.00-13.00'), ('inna', 'Inna')], max_length=20, verbose_name='Godziny pracy')),
                ('pickup_day', models.CharField(choices=[('pon', 'Poniedziałek'), ('wt', 'Wtorek'), ('śr', 'Środa'), ('czw', 'Czwartek'), ('pt', 'Piątek'), ('sb', 'Sobota')], max_length=20, verbose_name='Dni pracy')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mng', 'Kierownik'), ('drv', 'Kierowca')], max_length=20, verbose_name='Pełniona funkcja')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.IntegerField(verbose_name='Kod próbki')),
                ('sampling_date', models.TimeField(auto_now=True, verbose_name='Data pobrania')),
                ('delivery_date', models.TimeField(auto_now=True, verbose_name='Data dostawy')),
                ('in_delivery', models.BooleanField(verbose_name='W dostawie')),
                ('delivery_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_delivery', to='transport.Location', verbose_name='Miejsce dostawy')),
                ('drivers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Courier')),
                ('sampling_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Location', verbose_name='Miejsce pobrania')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='couriers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Courier'),
        ),
    ]
